acme_task:
    resource: "@AcmeTaskBundle/Resources/config/routing.yml"
    prefix:   /

acme_library:
    resource: "@AcmeLibraryBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller"
    type:     annotation
    


